[project]
name = "speciestrack"
version = "0.1.0"
description = "Native and invasive species tracking"
authors = [{ name = "Jacqui Manzi"}]
dependencies = ["requests"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"